from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
user_preferences={}

class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow, error):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(250, 130)
        self.centralwidget = QtWidgets.QWidget(OtherWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 390, 100))
        self.label.setText(error)
        self.label.setFont(font)
        self.label.setObjectName("label")
        OtherWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)
        OtherWindow.setWindowIcon(QtGui.QIcon('logo.png'))



    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "Error"))

class Ui_MainWindow(object):

    def openWindow(self,error): #Function to display error window, error is a string passed as a parameter
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OtherWindow()
        self.ui.setupUi(self.window,error)
        self.window.show()
    
    def enter_details(self,programme_drop_down):
        user_preferences['programme'] = self.programme_drop_down.currentText()
        if(len(self.construct_min.text().strip())>0 and len(self.construct_max.text().strip())>0): user_preferences['construct_in_sqmt'] = [int(self.construct_min.text().strip()),int(self.construct_max.text().strip())]    
        if(len(self.yoe_min.text().strip())>0 and len(self.yoe_max.text().strip())>0): user_preferences['year_of_establishment'] = [int(self.yoe_min.text().strip()),int(self.yoe_max.text().strip())]
        if(len(self.intake_min.text().strip())>0 and len(self.intake_max.text().strip())>0): user_preferences['intake'] = [int(self.intake_min.text().strip()),int(self.intake_max.text().strip())]
        if(self.autonomous.checkState()): user_preferences['autonomous']=True
        else: user_preferences['autonomous']=False
        if(self.has_diploma_courses.checkState()): user_preferences['has_diploma_courses']=True
        else: user_preferences['has_diploma_courses']=False
        if(self.specialized.checkState()): user_preferences['specialized']=True
        else: user_preferences['specialized']=False
        if(self.girl_exclusive.checkState()): user_preferences['girl_exclusive']=True
        else: user_preferences['girl_exclusive']=False
        if(self.staff_quarter_available.checkState()): user_preferences['staff_quarter_available']=True
        else: user_preferences['staff_quarter_available']=False
        if(self.accomodation_available.checkState()): user_preferences['accomodation_available']=True
        else: user_preferences['accomodation_available']=False
        if(self.student_hostel_available.checkState()): user_preferences['student_hostel_available']=True
        else: user_preferences['student_hostel_available']=False
        if(self.playground.checkState()): user_preferences['playground']='True'
        else: user_preferences['playground']='False'
        if(self.auditorium.checkState()): user_preferences['auditorium']='True'
        else: user_preferences['auditorium']='False'
        if(self.theatre.checkState()): user_preferences['theatre']='True'
        else: user_preferences['theatre']='False'
        if(self.library.checkState()): user_preferences['library']='True'
        else: user_preferences['library']='False'
        if(self.laboratory.checkState()): user_preferences['laboratory']='True'
        else: user_preferences['laboratory']='False'
        if(self.conference_hall.checkState()): user_preferences['conference_hall']='True'
        else: user_preferences['conference_hall']='False'
        if(self.health_center.checkState()): user_preferences['health_center']='True'
        else: user_preferences['health_center']='False'
        if(self.gymnasium_fitness_center.checkState()): user_preferences['gymnasium_fitness_center']='True'
        else: user_preferences['gymnasium_fitness_center']='False'
        if(self.indoor_stadium.checkState()): user_preferences['indoor_stadium']='True'
        else: user_preferences['indoor_stadium']='False'
        if(self.common_room.checkState()): user_preferences['common_room']='True'
        else: user_preferences['common_room']='False'
        if(self.computer_center.checkState()): user_preferences['computer_center']='True'
        else: user_preferences['computer_center']='False'
        if(self.cafeteria.checkState()): user_preferences['cafeteria']='True'
        else: user_preferences['cafeteria']='False'
        if(self.guest_house.checkState()): user_preferences['guest_house']='True'
        else: user_preferences['guest_house']='False'
        if(self.is_accredited.checkState()): user_preferences['is_accredited']='True'
        else: user_preferences['is_accredited']='False'

        
        print(user_preferences)
        f=open("UserPreferences.pkl","wb")
        pickle.dump(user_preferences,f)
        f.close()
        sys.exit(app.exec_())
        

        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 536)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.best_college_for_you = QtWidgets.QLabel(self.centralwidget)
        self.best_college_for_you.setGeometry(QtCore.QRect(200, 0, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.best_college_for_you.setFont(font)
        self.best_college_for_you.setObjectName("best_college_for_you")
        self.programme_drop_down = QtWidgets.QComboBox(self.centralwidget)
        self.programme_drop_down.setGeometry(QtCore.QRect(340, 40, 221, 22))
        self.programme_drop_down.setObjectName("programme_drop_down")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme_drop_down.addItem("")
        self.programme = QtWidgets.QLabel(self.centralwidget)
        self.programme.setGeometry(QtCore.QRect(20, 40, 71, 20))
        self.programme.setObjectName("programme")
        self.construct = QtWidgets.QLabel(self.centralwidget)
        self.construct.setGeometry(QtCore.QRect(20, 70, 231, 16))
        self.construct.setObjectName("construct")
        self.construct_min = QtWidgets.QLineEdit(self.centralwidget)
        self.construct_min.setGeometry(QtCore.QRect(340, 70, 71, 20))
        self.construct_min.setText("")
        self.construct_min.setObjectName("construct_min")
        self.construct_max = QtWidgets.QLineEdit(self.centralwidget)
        self.construct_max.setGeometry(QtCore.QRect(440, 70, 71, 20))
        self.construct_max.setObjectName("construct_max")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.yoe = QtWidgets.QLabel(self.centralwidget)
        self.yoe.setGeometry(QtCore.QRect(20, 100, 231, 16))
        self.yoe.setObjectName("yoe")
        self.yoe_max = QtWidgets.QLineEdit(self.centralwidget)
        self.yoe_max.setGeometry(QtCore.QRect(440, 100, 71, 20))
        self.yoe_max.setObjectName("yoe_max")
        self.y = QtWidgets.QLabel(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(420, 100, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.y.setFont(font)
        self.y.setObjectName("y")
        self.yoe_min = QtWidgets.QLineEdit(self.centralwidget)
        self.yoe_min.setGeometry(QtCore.QRect(340, 100, 71, 20))
        self.yoe_min.setText("")
        self.yoe_min.setObjectName("yoe_min")
        self.intake = QtWidgets.QLabel(self.centralwidget)
        self.intake.setGeometry(QtCore.QRect(20, 130, 231, 16))
        self.intake.setObjectName("intake")
        self.intake_max = QtWidgets.QLineEdit(self.centralwidget)
        self.intake_max.setGeometry(QtCore.QRect(440, 130, 71, 20))
        self.intake_max.setObjectName("intake_max")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(420, 130, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.intake_min = QtWidgets.QLineEdit(self.centralwidget)
        self.intake_min.setGeometry(QtCore.QRect(340, 130, 71, 20))
        self.intake_min.setText("")
        self.intake_min.setObjectName("intake_min")
        self.girl_exclusive_2 = QtWidgets.QLabel(self.centralwidget)
        self.girl_exclusive_2.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.girl_exclusive_2.setObjectName("girl_exclusive_2")
        self.student_hostel_available_2 = QtWidgets.QLabel(self.centralwidget)
        self.student_hostel_available_2.setGeometry(QtCore.QRect(20, 190, 131, 16))
        self.student_hostel_available_2.setObjectName("student_hostel_available_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 210, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 310, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 290, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 270, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 250, 81, 16))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 370, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 390, 81, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 350, 141, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 330, 81, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 410, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(340, 210, 111, 16))
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(340, 190, 81, 16))
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(340, 170, 81, 16))
        self.label_24.setObjectName("label_24")
        self.student_hostel_available = QtWidgets.QCheckBox(self.centralwidget)
        self.student_hostel_available.setGeometry(QtCore.QRect(190, 190, 70, 17))
        self.student_hostel_available.setText("")
        self.student_hostel_available.setObjectName("student_hostel_available")
        self.common_room = QtWidgets.QCheckBox(self.centralwidget)
        self.common_room.setGeometry(QtCore.QRect(190, 390, 70, 17))
        self.common_room.setText("")
        self.common_room.setObjectName("common_room")
        self.gymnasium_fitness_center = QtWidgets.QCheckBox(self.centralwidget)
        self.gymnasium_fitness_center.setGeometry(QtCore.QRect(190, 350, 70, 17))
        self.gymnasium_fitness_center.setText("")
        self.gymnasium_fitness_center.setObjectName("gymnasium_fitness_center")
        self.laboratory = QtWidgets.QCheckBox(self.centralwidget)
        self.laboratory.setGeometry(QtCore.QRect(190, 230, 70, 17))
        self.laboratory.setText("")
        self.laboratory.setObjectName("laboratory")
        self.library = QtWidgets.QCheckBox(self.centralwidget)
        self.library.setGeometry(QtCore.QRect(190, 210, 70, 17))
        self.library.setText("")
        self.library.setObjectName("library")
        self.cafeteria = QtWidgets.QCheckBox(self.centralwidget)
        self.cafeteria.setGeometry(QtCore.QRect(190, 290, 70, 17))
        self.cafeteria.setText("")
        self.cafeteria.setObjectName("cafeteria")
        self.girl_exclusive = QtWidgets.QCheckBox(self.centralwidget)
        self.girl_exclusive.setGeometry(QtCore.QRect(190, 170, 70, 17))
        self.girl_exclusive.setText("")
        self.girl_exclusive.setObjectName("girl_exclusive")
        self.health_center = QtWidgets.QCheckBox(self.centralwidget)
        self.health_center.setGeometry(QtCore.QRect(190, 330, 70, 17))
        self.health_center.setText("")
        self.health_center.setObjectName("health_center")
        self.conference_hall = QtWidgets.QCheckBox(self.centralwidget)
        self.conference_hall.setGeometry(QtCore.QRect(190, 250, 70, 17))
        self.conference_hall.setText("")
        self.conference_hall.setObjectName("conference_hall")
        self.theatre = QtWidgets.QCheckBox(self.centralwidget)
        self.theatre.setGeometry(QtCore.QRect(190, 310, 70, 17))
        self.theatre.setText("")
        self.theatre.setObjectName("theatre")
        self.computer_center = QtWidgets.QCheckBox(self.centralwidget)
        self.computer_center.setGeometry(QtCore.QRect(190, 270, 70, 17))
        self.computer_center.setText("")
        self.computer_center.setObjectName("computer_center")
        self.indoor_stadium = QtWidgets.QCheckBox(self.centralwidget)
        self.indoor_stadium.setGeometry(QtCore.QRect(190, 370, 70, 17))
        self.indoor_stadium.setText("")
        self.indoor_stadium.setObjectName("indoor_stadium")
        self.guest_house = QtWidgets.QCheckBox(self.centralwidget)
        self.guest_house.setGeometry(QtCore.QRect(190, 410, 70, 17))
        self.guest_house.setText("")
        self.guest_house.setObjectName("guest_house")
        self.has_diploma_courses = QtWidgets.QCheckBox(self.centralwidget)
        self.has_diploma_courses.setGeometry(QtCore.QRect(470, 210, 70, 17))
        self.has_diploma_courses.setText("")
        self.has_diploma_courses.setObjectName("has_diploma_courses")
        self.autonomous = QtWidgets.QCheckBox(self.centralwidget)
        self.autonomous.setGeometry(QtCore.QRect(470, 190, 70, 17))
        self.autonomous.setText("")
        self.autonomous.setObjectName("autonomous")
        self.is_accredited = QtWidgets.QCheckBox(self.centralwidget)
        self.is_accredited.setGeometry(QtCore.QRect(470, 170, 70, 17))
        self.is_accredited.setText("")
        self.is_accredited.setObjectName("is_accredited")
        self.specialized = QtWidgets.QCheckBox(self.centralwidget)
        self.specialized.setGeometry(QtCore.QRect(470, 230, 70, 17))
        self.specialized.setText("")
        self.specialized.setObjectName("specialized")
        self.staff_quarter_available = QtWidgets.QCheckBox(self.centralwidget)
        self.staff_quarter_available.setGeometry(QtCore.QRect(470, 250, 70, 17))
        self.staff_quarter_available.setText("")
        self.staff_quarter_available.setObjectName("staff_quarter_available")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(340, 250, 131, 16))
        self.label_25.setObjectName("label_25")
        self.accomodation_available = QtWidgets.QCheckBox(self.centralwidget)
        self.accomodation_available.setGeometry(QtCore.QRect(470, 270, 70, 17))
        self.accomodation_available.setText("")
        self.accomodation_available.setObjectName("accomodation_available")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(340, 270, 121, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(340, 230, 81, 16))
        self.label_27.setObjectName("label_27")
        self.playground = QtWidgets.QCheckBox(self.centralwidget)
        self.playground.setGeometry(QtCore.QRect(190, 430, 70, 17))
        self.playground.setText("")
        self.playground.setObjectName("playground")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(20, 430, 81, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 450, 81, 16))
        self.label_29.setObjectName("label_29")
        self.auditorium = QtWidgets.QCheckBox(self.centralwidget)
        self.auditorium.setGeometry(QtCore.QRect(190, 450, 70, 17))
        self.auditorium.setText("")
        self.auditorium.setObjectName("auditorium")
        self.enterDetails = QtWidgets.QPushButton(self.centralwidget)
        self.enterDetails.setGeometry(QtCore.QRect(240, 480, 75, 23))
        self.enterDetails.setObjectName("enterDetails")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.enterDetails.clicked.connect(self.enter_details)

        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setWindowIcon(QtGui.QIcon('logo.png'))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Select Preferences"))
        self.best_college_for_you.setText(_translate("MainWindow", "Best College for You"))
        self.programme_drop_down.setItemText(0, _translate("MainWindow", "B.Com.-Bachelor of Commerce"))
        self.programme_drop_down.setItemText(1, _translate("MainWindow", "M.Com.-Master of Commerce"))
        self.programme_drop_down.setItemText(2, _translate("MainWindow", "B.C.A.-Bachelor of Computer Applications"))
        self.programme_drop_down.setItemText(3, _translate("MainWindow", "M.C.A. -Master of Computer Applications"))
        self.programme_drop_down.setItemText(4, _translate("MainWindow", "M.A.-Master of Arts"))
        self.programme_drop_down.setItemText(5, _translate("MainWindow", "M.Pharm. -Master of Pharmacy"))
        self.programme_drop_down.setItemText(6, _translate("MainWindow", "B.H.M.S.-Bachelor of Homeopathic Medicine and Surgery"))
        self.programme_drop_down.setItemText(7, _translate("MainWindow", "B.S.W.-Bachelor of Social Work"))
        self.programme_drop_down.setItemText(8, _translate("MainWindow", "L.L.B.-Bachelor of Law or Laws"))
        self.programme_drop_down.setItemText(9, _translate("MainWindow", "M.Sc.-Master of Science"))
        self.programme_drop_down.setItemText(10, _translate("MainWindow", "B.Tech.-Bachelor of Technology"))
        self.programme_drop_down.setItemText(11, _translate("MainWindow", "M.Ed. -Master of Education"))
        self.programme_drop_down.setItemText(12, _translate("MainWindow", "PG Diploma-Post Graduate Diploma"))
        self.programme_drop_down.setItemText(13, _translate("MainWindow", "B.P.T.-Bachelor of Physiotherapy"))
        self.programme_drop_down.setItemText(14, _translate("MainWindow", "B.Architecture-Bachelor of Architecture"))
        self.programme_drop_down.setItemText(15, _translate("MainWindow", "M.B.A.- Master of Business Administration"))
        self.programme_drop_down.setItemText(16, _translate("MainWindow", "B.E.-Bachelor of Engineering"))
        self.programme_drop_down.setItemText(17, _translate("MainWindow", "M.E.-Master of Engineering"))
        self.programme_drop_down.setItemText(18, _translate("MainWindow", "M.Sc. Nursing-Master of Science in Nursing"))
        self.programme_drop_down.setItemText(19, _translate("MainWindow", "M.Tech. -Master of Technology"))
        self.programme_drop_down.setItemText(20, _translate("MainWindow", "B.Sc.(Nursing)-Bachelor of Science in Nursing"))
        self.programme_drop_down.setItemText(21, _translate("MainWindow", "B.Sc.(Post Basic)-B.Sc (Post Basic)"))
        self.programme_drop_down.setItemText(22, _translate("MainWindow", "Ph.D.-Doctor of Philosophy"))
        self.programme_drop_down.setItemText(23, _translate("MainWindow", "M.D.-Doctor of Medicine"))
        self.programme_drop_down.setItemText(24, _translate("MainWindow", "B.B.M.-Bachelor of Business Management"))
        self.programme_drop_down.setItemText(25, _translate("MainWindow", "B.A.(Hons)-Bachelor of Arts (Honors)"))
        self.programme_drop_down.setItemText(26, _translate("MainWindow", "B.Sc.(Hons)-Bachelor of Science (Honors)"))
        self.programme_drop_down.setItemText(27, _translate("MainWindow", "B.F.A.-Bachelor of Fine Arts"))
        self.programme_drop_down.setItemText(28, _translate("MainWindow", "B.A. L.L.B.-Bachelor of Arts, Bachelor of Law or Laws"))
        self.programme_drop_down.setItemText(29, _translate("MainWindow", "B.P.Ed.-Bachelor of Physical Education"))
        self.programme_drop_down.setItemText(30, _translate("MainWindow", "M.B.B.S.-Bachelor of Medicine and Bachelor of Surgery"))
        self.programme_drop_down.setItemText(31, _translate("MainWindow", "D.Pharma-Diploma in Pharmacy"))
        self.programme_drop_down.setItemText(32, _translate("MainWindow", "B.A. B.Ed.-Bachelor of Arts, Bachelor of Education"))
        self.programme.setText(_translate("MainWindow", "<html><head/><body><p>Programme:</p></body></html>"))
        self.construct.setText(_translate("MainWindow", "Construct in sqmt (min=100, max=1000000):"))
        self.label_4.setText(_translate("MainWindow", "-"))
        self.yoe.setText(_translate("MainWindow", "Year of Establishment (min=1810, max=2016):"))
        self.y.setText(_translate("MainWindow", "-"))
        self.intake.setText(_translate("MainWindow", "Intake (min=100, max=15000):"))
        self.label_8.setText(_translate("MainWindow", "-"))
        self.girl_exclusive_2.setText(_translate("MainWindow", "Girl Exclusive:"))
        self.student_hostel_available_2.setText(_translate("MainWindow", "Student Hostel Available:"))
        self.label_11.setText(_translate("MainWindow", "Laboratories:"))
        self.label_12.setText(_translate("MainWindow", "Library:"))
        self.label_13.setText(_translate("MainWindow", "Theatre:"))
        self.label_14.setText(_translate("MainWindow", "Cafeteria:"))
        self.label_15.setText(_translate("MainWindow", "Computer Center: "))
        self.label_16.setText(_translate("MainWindow", "Conference Hall:"))
        self.label_18.setText(_translate("MainWindow", "Indoor Stadium: "))
        self.label_20.setText(_translate("MainWindow", "Common Room:"))
        self.label_21.setText(_translate("MainWindow", "Gymnasium/Fitness Center:"))
        self.label_22.setText(_translate("MainWindow", "Health Center:"))
        self.label_23.setText(_translate("MainWindow", "Guest House:"))
        self.label_17.setText(_translate("MainWindow", "Has Diploma Courses: "))
        self.label_19.setText(_translate("MainWindow", "Autonomous:"))
        self.label_24.setText(_translate("MainWindow", "Is Accredited:"))
        self.label_25.setText(_translate("MainWindow", "Staff Quarter Available:"))
        self.label_26.setText(_translate("MainWindow", "Accomodation Available: "))
        self.label_27.setText(_translate("MainWindow", "Specialized:"))
        self.label_28.setText(_translate("MainWindow", "Playground:"))
        self.label_29.setText(_translate("MainWindow", "Auditorium:"))
        self.enterDetails.setText(_translate("MainWindow", "Enter Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())

